name: test
config:
  auth_providers:
    - opsgenie
nodes:
  - !Http
    id: get_uuid
    url: https://httpbin.org/uuid
    method: GET
  - !Http
    id: create_todo
    url: https://httpbin.org/anything/todos
    method: POST
    body: |
      {{ { "fields": input, "id": get_uuid.uuid } }}
  - !Condition
    id: if_a_condition
    expression: "{{create_todo.json.fields.aBool)}}"
    true_branch:
      - !Http
        id: update_todo
        url: "{{join('', ['https://httpbin.org/anything/todos/', create_todo.json.id])}}"
        method: PATCH
        body: |
          {{
          {
            "updated_true": create_todo.json.phone
          }
          }}
    false_branch:
      - !Http
        id: put_todo
        url: "{{join('', ['https://httpbin.org/anything/todos/', create_todo.json.id])}}"
        method: PUT
        body: "{{input}}"
  - !Branch
    id: switch_case
    branches:
      case_1:
        - !Http
          id: delete_todo
          url: "{{join('', ['https://httpbin.org/anything/todos/', create_todo.json.id])}}"
          method: DELETE
  - !Assertion
    id: assert_data
    assertions:
      - !Equals
        left: "{{create_todo.json.message}}"
        right: "{{create_todo.json.message}}"
      - !NotEquals
        left: "{{create_todo.json.x}}"
        right: "{{create_todo.json.y}}"
